# Generated by Django 6.0.4 on 2026-04-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a service image', null=True, upload_to='services/'),
        ),
    ]
