# Generated by Django 6.0.4 on 2026-04-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload your profile photo', null=True, upload_to='profile_photos/'),
        ),
    ]
